from passrotate.providers.amazon import Amazon
from passrotate.providers.cloudflare import Cloudflare
from passrotate.providers.digitalocean import DigitalOcean
from passrotate.providers.github import GitHub
from passrotate.providers.linode import Linode
from passrotate.providers.namecheap import Namecheap
from passrotate.providers.pixiv import Pixiv
from passrotate.providers.twitter import Twitter
from passrotate.providers.ycombinator import YCombinator
